In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[3,4,5]])

In [3]:
array =np.zeros((5,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
array = np.ones( (5,5) )
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
array1 = np.random.randn()
array2 = np.random.rand()
array3 = np.matrix(array)
print(array1)
print(array2)
print(array3)

-0.5197461561532739
0.4401951664305478
[[-0.35704165]]


In [15]:
for i in range(1,101):
  if i%3==0 or i%5==0:
    print(i)

2
4
5
6
8
10
12
14
15
16
18
20
22
24
25
26
28
30
32
34
35
36
38
40
42
44
45
46
48
50
52
54
55
56
58
60
62
64
65
66
68
70
72
74
75
76
78
80
82
84
85
86
88
90
92
94
95
96
98
100


In [17]:
def circleArea(radius):
    area = float(radius) * float(radius)*3.14
    print ("Area :",area)
    return area
 
r = input("Enter redius :")
 
circleArea(r)

Enter redius :8
Area : 200.96


200.96

In [21]:
favorite_season = "Summer"

if favorite_season == "Winter":
    print("That is my favorite season too")
elif favorite_season == "Summer":
    print("Summer is amazing")
elif favorite_season == "Spring":
    print("I love spring")
else:
    print("Fall is my mom's favorite season")

Summer is amazing


In [26]:
x = 6
while x < 15:
    if x % 2 == 0:
        x += 1
        continue
    print("Odd:", x)
    x += 1

Odd: 7
Odd: 9
Odd: 11
Odd: 13


In [35]:
def print_pattern(num_rows):
    for i in range(num_rows):
        for num_cols in range(num_rows-i):
            print("*", end="")
        print()

In [36]:
print_pattern(5)

*****
****
***
**
*
